adds missing proxied binaries to the tarball list
ferrocene/ferrocene pull request #470
Opened 2024-04-02 14:34 UTC by amanjeev

Ticket: 86944n9mw

2024-04-02 14:36 UTC, amanjeev commented
bors try

2024-04-02 17:19 UTC, amanjeev commented
bors try

2024-04-02 17:51 UTC, amanjeev commented
bors try

2024-04-02 18:11 UTC, amanjeev commented
bors try

2024-04-03 07:51 UTC, pietroalbini requested changes
That wasn't supposed to be an approval

2024-04-03 13:52 UTC, amanjeev commented on src/bootstrap/src/core/build_steps/dist.rs
> +        tarball.ferrocene_proxied_binary("bin/clippy");
hahaha I assumed those were there for a reason. damn I must not trust the code I get.

2024-04-03 14:29 UTC, amanjeev commented
bors try

2024-04-03 16:25 UTC, amanjeev commented
This is ready.

2024-04-04 08:03 UTC, pietroalbini approved these changes
bors merge

2024-04-04 10:33 UTC, merged