be more clear by including variants of the error
ferrocene/ferrocene pull request #529
Opened 2024-04-17 18:37 UTC by tshepang

2024-04-18 13:23 UTC, tshepang commented on ferrocene/tools/self-test/src/error.rs
> +    #[error("; found symlink instead")]
I did not know what to write in addition to "binary foo not found (inside dir)" (see line 218). Maybe "No other file found"?

2024-04-18 18:07 UTC, Hoverbear commented on ferrocene/tools/self-test/src/error.rs
> +    #[error("; found symlink instead")]
The content otherwise is fine, just the `; ` seems to be problematic?

2024-04-22 13:03 UTC, pietroalbini requested changes
What's the reason for this change?

2024-04-22 13:03 UTC, pietroalbini commented on ferrocene/tools/self-test/src/binaries.rs
> +        std::os::windows::fs::symlink_file(&original, &link).unwrap();
This means the test suite will break if the user is on a Windows system without symlinks enabled.

2024-04-22 18:55 UTC, tshepang commented
> What's the reason for this change?

it's to give a better (more detailed) error message than just "binary foo not found", since it can be misleading in that it can seem to imply that no file at all is found

2024-04-23 09:03 UTC, pietroalbini commented
Then I'd just change the error message to be "the binary we expected is not there", which can imply the binary being missing, the binary being a directory, or being a symlink. In the end users shouldn't care about the actual cause, since the fix will be "reinstall ferrocene".

2024-04-23 21:01 UTC, tshepang commented
now less bloated, and hopefully more clear than previously

2024-04-24 13:53 UTC, Urhengulas approved these changes
bors merge

2024-04-24 23:57 UTC, tshepang commented
bors merge

2024-04-25 01:12 UTC, merged