Enable aarch64-darwin tests
ferrocene/ferrocene pull request #671
Opened 2024-06-05 18:16 UTC by Hoverbear

Enable tests on aarch64-darwin.

2024-06-05 18:23 UTC, Hoverbear commented
bors try

2024-06-05 18:42 UTC, Hoverbear commented
bors try-

(Waiting for #670)

2024-06-06 15:22 UTC, Hoverbear commented
bors try

2024-06-21 14:19 UTC, Hoverbear commented
Noting this is not a priority for us at this time.

2024-07-25 19:12 UTC, Hoverbear commented
Looks like we have ~4 failing tests: 

```
failures:
    [run-make] tests/run-make/fix-cortex-a53-843419
    [run-make] tests/run-make/ferrocene/compiler-arguments/upper_c_debuginfo/upper_c_debuginfo_multiple
    [run-make] tests/run-make/ferrocene/compiler-arguments/upper_c_rpath/upper_c_rpath
    [run-make] tests/run-make/ferrocene/compiler-arguments/upper_c_metadata/upper_c_metadata
```

2024-07-29 15:27 UTC, Hoverbear commented
bors try

2024-07-30 16:01 UTC, Hoverbear commented
bors try

2024-07-30 19:10 UTC, Hoverbear commented
This failed due to a transient condition, and a rerun worked.

2024-08-01 12:36 UTC, pietroalbini requested changes

2024-08-01 12:36 UTC, pietroalbini commented on tests/run-make/ferrocene/compiler-arguments/upper_c_debuginfo/upper_c_debuginfo_multiple/Makefile
> +#   On Mac, signatures mean that the diff'd files are not equal when we expect them to be.
This should be in the same line, as otherwise it's not marked as the reason for the ignore (applies to all similar changes).

2024-08-01 12:36 UTC, pietroalbini commented on tests/ui/ferrocene/compiler-arguments/upper_c_target-cpu/upper_c_target-cpu_invalid.rs
> +//    On aarch64 this test does not produce the final line of the stderr about 64 bit code
Same line.

2024-08-02 13:19 UTC, pietroalbini approved these changes
bors merge

2024-08-02 17:48 UTC, merged